In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/serie_a_matches.csv')

In [3]:
df.head()

,area,competition,season,id,utcDate,status,matchday,stage,group,lastUpdated,homeTeam,awayTeam,score,odds,referees
0,"{'id': 2114, 'name': 'Italy', 'code': 'ITA', '...","{'id': 2019, 'name': 'Serie A', 'code': 'SA', ...","{'id': 2310, 'startDate': '2024-08-18', 'endDa...",503046,2024-08-17T16:30:00Z,FINISHED,1,REGULAR_SEASON,NaN,2025-01-07T00:20:47Z,"{'id': 107, 'name': 'Genoa CFC', 'shortName': ...","{'id': 108, 'name': 'FC Internazionale Milano'...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",{'msg': 'Activate Odds-Package in User-Panel t...,"[{'id': 57882, 'name': 'Ermanno Feliciani', 't..."
1,"{'id': 2114, 'name': 'Italy', 'code': 'ITA', '...","{'id': 2019, 'name': 'Serie A', 'code': 'SA', ...","{'id': 2310, 'startDate': '2024-08-18', 'endDa...",503052,2024-08-17T16:30:00Z,FINISHED,1,REGULAR_SEASON,NaN,2025-01-07T00:20:47Z,"{'id': 112, 'name': 'Parma Calcio 1913', 'shor...","{'id': 99, 'name': 'ACF Fiorentina', 'shortNam...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",{'msg': 'Activate Odds-Package in User-Panel t...,"[{'id': 57842, 'name': 'Giovanni Ayroldi', 'ty..."
2,"{'id': 2114, 'name': 'Italy', 'code': 'ITA', '...","{'id': 2019, 'name': 'Serie A', 'code': 'SA', ...","{'id': 2310, 'startDate': '2024-08-18', 'endDa...",503045,2024-08-17T18:45:00Z,FINISHED,1,REGULAR_SEASON,NaN,2025-01-07T00:20:47Z,"{'id': 445, 'name': 'Empoli FC', 'shortName': ...","{'id': 5911, 'name': 'AC Monza', 'shortName': ...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",{'msg': 'Activate Odds-Package in User-Panel t...,"[{'id': 10985, 'name': 'Michael Fabbri', 'type..."
3,"{'id': 2114, 'name': 'Italy', 'code': 'ITA', '...","{'id': 2019, 'name': 'Serie A', 'code': 'SA', ...","{'id': 2310, 'startDate': '2024-08-18', 'endDa...",503051,2024-08-17T18:45:00Z,FINISHED,1,REGULAR_SEASON,NaN,2025-01-07T00:20:47Z,"{'id': 98, 'name': 'AC Milan', 'shortName': 'M...","{'id': 586, 'name': 'Torino FC', 'shortName': ...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",{'msg': 'Activate Odds-Package in User-Panel t...,"[{'id': 10977, 'name': 'Fabio Maresca', 'type'..."
4,"{'id': 2114, 'name': 'Italy', 'code': 'ITA', '...","{'id': 2019, 'name': 'Serie A', 'code': 'SA', ...","{'id': 2310, 'startDate': '2024-08-18', 'endDa...",503043,2024-08-18T16:30:00Z,FINISHED,1,REGULAR_SEASON,NaN,2025-01-07T00:20:47Z,"{'id': 103, 'name': 'Bologna FC 1909', 'shortN...","{'id': 115, 'name': 'Udinese Calcio', 'shortNa...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",{'msg': 'Activate Odds-Package in User-Panel t...,"[{'id': 212567, 'name': 'Maria Caputi', 'type'..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   area         380 non-null    object
 1   competition  380 non-null    object
 2   season       380 non-null    object
 3   id           380 non-null    int64
 4   utcDate      380 non-null    object
 5   status       380 non-null    object
 6   matchday     380 non-null    int64
 7   stage        380 non-null    object
 8   group        0 non-null      float64
 9   lastUpdated  380 non-null    object
 10  homeTeam     380 non-null    object
 11  awayTeam     380 non-null    object
 12  score        380 non-null    object
 13  odds         380 non-null    object
 14  referees     380 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 44.7+ KB

In [5]:
df.drop(columns=['area', 'competition', 'season', 'stage', 'lastUpdated', 'odds', 'group', 'referees'], axis=1, inplace=True)

In [6]:
df['date_month'] = df['utcDate'].str.split('T').str[0].str[5:7]
df['time_hour'] = df['utcDate'].str.split('T').str[1].str.replace('Z', '').str[:2]

In [7]:
df.drop('utcDate', axis=1, inplace=True)

In [8]:
df.head()

,id,status,matchday,homeTeam,awayTeam,score,date_month,time_hour
0,503046,FINISHED,1,"{'id': 107, 'name': 'Genoa CFC', 'shortName': ...","{'id': 108, 'name': 'FC Internazionale Milano'...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,16
1,503052,FINISHED,1,"{'id': 112, 'name': 'Parma Calcio 1913', 'shor...","{'id': 99, 'name': 'ACF Fiorentina', 'shortNam...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,16
2,503045,FINISHED,1,"{'id': 445, 'name': 'Empoli FC', 'shortName': ...","{'id': 5911, 'name': 'AC Monza', 'shortName': ...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,18
3,503051,FINISHED,1,"{'id': 98, 'name': 'AC Milan', 'shortName': 'M...","{'id': 586, 'name': 'Torino FC', 'shortName': ...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,18
4,503043,FINISHED,1,"{'id': 103, 'name': 'Bologna FC 1909', 'shortN...","{'id': 115, 'name': 'Udinese Calcio', 'shortNa...","{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,16

In [9]:
import ast

def extract_short_name(team_str):
    team_dict = ast.literal_eval(team_str)
    return team_dict['shortName']

df['homeTeam'] = df['homeTeam'].apply(extract_short_name)
df['awayTeam'] = df['awayTeam'].apply(extract_short_name)

In [10]:
df.head()

,id,status,matchday,homeTeam,awayTeam,score,date_month,time_hour
0,503046,FINISHED,1,Genoa,Inter,"{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,16
1,503052,FINISHED,1,Parma,Fiorentina,"{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,16
2,503045,FINISHED,1,Empoli,Monza,"{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,18
3,503051,FINISHED,1,Milan,Torino,"{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,18
4,503043,FINISHED,1,Bologna,Udinese,"{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...",08,16

In [11]:
def fulltime_home(team_str):
    team_dict = ast.literal_eval(team_str)
    return team_dict['fullTime']['home']
def fulltime_away(team_str):
    team_dict = ast.literal_eval(team_str)
    return team_dict['fullTime']['away']
def halftime_home(team_str):
    team_dict = ast.literal_eval(team_str)
    return team_dict['halfTime']['home']
def halftime_away(team_str):
    team_dict = ast.literal_eval(team_str)
    return team_dict['halfTime']['away']

In [12]:
df['ft_home'] = df['score'].apply(fulltime_home)
df['ft_away'] = df['score'].apply(fulltime_away)
df['ht_home'] = df['score'].apply(halftime_home)
df['ht_away'] = df['score'].apply(halftime_away)

In [13]:
df.loc[0]['score']

"{'winner': 'DRAW', 'duration': 'REGULAR', 'fullTime': {'home': 2, 'away': 2}, 'halfTime': {'home': 1, 'away': 1}}"

In [14]:
df.drop('score', axis=1, inplace=True)

In [15]:
df.head()

,id,status,matchday,homeTeam,awayTeam,date_month,time_hour,ft_home,ft_away,ht_home,ht_away
0,503046,FINISHED,1,Genoa,Inter,08,16,2.0,2.0,1.0,1.0
1,503052,FINISHED,1,Parma,Fiorentina,08,16,1.0,1.0,1.0,0.0
2,503045,FINISHED,1,Empoli,Monza,08,18,0.0,0.0,0.0,0.0
3,503051,FINISHED,1,Milan,Torino,08,18,2.0,2.0,0.0,1.0
4,503043,FINISHED,1,Bologna,Udinese,08,16,1.0,1.0,0.0,0.0

In [16]:
df['winner'] = df.apply(lambda row: 0 if row['ft_home'] > row['ft_away'] else (1 if row['ft_home'] == row['ft_away'] else 2), axis=1)

In [17]:
df.head(20)

,id,status,matchday,homeTeam,awayTeam,date_month,time_hour,ft_home,ft_away,ht_home,ht_away,winner
0,503046,FINISHED,1,Genoa,Inter,08,16,2.0,2.0,1.0,1.0,1
1,503052,FINISHED,1,Parma,Fiorentina,08,16,1.0,1.0,1.0,0.0,1
2,503045,FINISHED,1,Empoli,Monza,08,18,0.0,0.0,0.0,0.0,1
3,503051,FINISHED,1,Milan,Torino,08,18,2.0,2.0,0.0,1.0,1
4,503043,FINISHED,1,Bologna,Udinese,08,16,1.0,1.0,0.0,0.0,1
5,503047,FINISHED,1,Verona,Napoli,08,16,3.0,0.0,0.0,0.0,0
6,503044,FINISHED,1,Cagliari,Roma,08,18,0.0,0.0,0.0,0.0,1
7,503049,FINISHED,1,Lazio,Venezia FC,08,18,3.0,1.0,2.0,1.0,0
8,503050,FINISHED,1,Lecce,Atalanta,08,16,0.0,4.0,0.0,2.0,2
9,503048,FINISHED,1,Juventus,Como 1907,08,18,3.0,0.0,2.0,0.0,0
10,503059,FINISHED,2,Parma,Milan,08,16,2.0,1.0,1.0,0.0,0
11,503062,FINISHED,2,Udinese,Lazio,08,16,2.0,1.0,1.0,0.0,0
12,503056,FINISHED,2,Inter,Lecce,08,18,2.0,0.0,1.0,0.0,0
13,503057,FINISHED,2,Monza,Genoa,08,18,0.0,1.0,0.0,1.0,2
14,503054,FINISHED,2,Fiorentina,Venezia FC,08,16,0.0,0.0,0.0,0.0,1
15,503061,FINISHED,2,Torino,Atalanta,08,16,2.0,1.0,1.0,1.0,0
16,503058,FINISHED,2,Napoli,Bologna,08,18,3.0,0.0,1.0,0.0,0
17,503060,FINISHED,2,Roma,Empoli,08,18,1.0,2.0,0.0,1.0,2
18,503053,FINISHED,2,Cagliari,Como 1907,08,16,1.0,1.0,1.0,0.0,1
19,503055,FINISHED,2,Verona,Juventus,08,18,0.0,3.0,0.0,2.0,2

In [18]:
df.to_csv('../data/serie_a_matches_cleaned.csv', index=False)